// src/pages/curriculum/igcse/subjectsList.vue
<template>
  <div class="mt-8 bg-gray-300 px-4 py-4 md:mx-8 md:rounded-xl md:px-8">
    <h2 class="text-center text-4xl">Choose Your Major</h2>
    <div class="mt-12">
      <div class="grid grid-cols-2 gap-2 md:grid-cols-5">
        <button
          class="flex flex-col items-center justify-center gap-5 rounded-lg bg-primary px-4 py-4 text-white"
          v-for="(major, index) in majors"
          :key="index"
          @click="onMajorClick(major.name)"
        >
          <img
            :src="major.icon"
            :alt="`${major.name} Icon`"
            width="100"
            height="100"
          />
          <div>{{ major.name }}</div>
        </button>
      </div>
    </div>
  </div>

  <div class="mx-8 mt-12">
    <h2 class="mb-8 text-4xl">Subject Guide</h2>
    <div
      class="flex flex-col gap-12 md:flex-row md:gap-0"
      v-if="currentMajor.name != ''"
    >
      <div class="flex-1">
        <h3 class="mb-4 text-xl md:text-3xl">Core Subjects</h3>
        <div v-for="(subject, index) in currentMajor.coreSubjects" :key="index">
          {{ subject }}
        </div>
      </div>
      <div class="flex-1">
        <h3 class="mb-4 text-xl md:text-3xl">Non-Essential Subjects</h3>
        <div
          v-for="(subject, index) in currentMajor.optionalSubjects"
          :key="index"
        >
          {{ subject }}
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, onMounted } from "vue";
import { majors } from "./subjectsData";

export default defineComponent({
  name: "SubjectList",
  components: {},
  setup() {
    const defaultMajor = {
      icon: "",
      name: "",
      coreSubjects: [],
      optionalSubjects: [],
    };
    const currentMajor = reactive(defaultMajor);

    const onMajorClick = (majorName: string) => {
      const selectedMajor = majors.filter((major) => {
        return major.name == majorName;
      });

      for (const key in selectedMajor[0]) {
        currentMajor[key] = selectedMajor[0][key];
      }
    };

    return { majors, currentMajor, onMajorClick };
  },
});

// <a href="https://www.flaticon.com/free-icons/medical" title="medical icons">Medical icons created by Freepik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/engineer" title="engineer icons">Engineer icons created by Eucalyp - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/computer-science" title="computer-science icons">Computer-science icons created by Freepik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/business" title="business icons">Business icons created by Freepik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/budget" title="budget icons">Budget icons created by Freepik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/recession" title="recession icons">Recession icons created by Freepik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/law" title="law icons">Law icons created by Freepik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/psychology" title="psychology icons">Psychology icons created by Freepik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/biologist" title="biologist icons">Biologist icons created by monkik - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/art" title="art icons">Art icons created by Freepik - Flaticon</a>
</script>

// src/pages/curriculum/a-level/subjectsList.tsx
import { useState } from "react";
import { Major, majors } from "./subjectsData";

const subjectsList = () => {
  const defaultMajor = {
    icon: "",
    name: "",
    coreSubjects: [],
    optionalSubjects: [],
  };
  const [currentMajor, setCurrentMajor] = useState(defaultMajor as Major);

  const onMajorClick = (majorName: string) => {
    const selectedMajor = majors.filter((major) => {
      return major.name == majorName;
    });
    setCurrentMajor(selectedMajor[0]);
  };

  return (
    <>
      <div className="mt-8 bg-gray-300 px-4 py-4 md:mx-8 md:rounded-xl md:px-8">
        <h2 className="text-center text-4xl">Choose Your Major</h2>
        <div className="mt-12">
          <div className="grid grid-cols-2 gap-2 md:grid-cols-5">
            {majors.map((major) => {
              return (
                <button
                  key={major.name}
                  onClick={() => onMajorClick(major?.name ?? "")}
                  className="flex flex-col items-center justify-center gap-5 rounded-lg bg-primary px-4 py-4 text-white hover:bg-primary/90 active:bg-primary/95"
                >
                  <img
                    src={major.icon}
                    alt={`${major.name} Icon`}
                    width="100"
                    height="100"
                  />
                  <div>{major.name}</div>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      <div className="mx-8 mt-12">
        <h2 className="mb-8 text-4xl">Subject Guide</h2>
        {!!currentMajor.name ? (
          <div
            className="flex flex-col gap-12 md:flex-row md:gap-0"
            v-if="currentMajor.name != ''"
          >
            <div className="flex-1">
              <h3 className="mb-4 text-xl md:text-3xl">Core Subjects</h3>
              {currentMajor.coreSubjects.map((subject) => {
                return <div key={subject}>{subject}</div>;
              })}
            </div>
            <div className="flex-1">
              <h3 className="mb-4 text-xl md:text-3xl">
                Non-Essential Subjects
              </h3>
              {currentMajor.optionalSubjects.map((subject) => {
                return <div key={subject}>{subject}</div>;
              })}
            </div>
          </div>
        ) : (
          <></>
        )}
      </div>
    </>
  );
};

export default subjectsList;
